twig:
    default_path: '%kernel.project_dir%/templates'
    date:
        format: 'd.m.Y'
    globals:
        invoice_helper: '@App\Service\InvoiceHelper'

when@test:
    twig:
        strict_variables: true
