twig:
    default_path: '%kernel.project_dir%/templates'
    date:
        format: 'd.m.Y'
    globals:
        invoice_entry_helper: '@App\Service\InvoiceEntryHelper'

when@test:
    twig:
        strict_variables: true
