services:
  phpfpm:
    environment:
      - CRONFILE=/app/crontab.prod
    volumes:
      - ../../shared/.env.local:/app/.env.local

  supervisor:
    volumes:
      - ../../shared/.env.local:/app/.env.local
