services:
    phpfpm:
        environment:
            - PHP_MEMORY_LIMIT=256M

    supervisor:
        image: itkdev/supervisor-php8.3:alpine
        restart: unless-stopped
        stop_grace_period: 20s
        environment:
            - APP_SUPERVISOR_COMMAND=/app/bin/console messenger:consume --env=prod --no-debug --time-limit=900 --failure-limit=1 async scheduler_default
            - APP_SUPERVISOR_WORKERS=4
            - APP_SUPERVISOR_USER=deploy
            - PHP_MAX_EXECUTION_TIME=60
            - PHP_MEMORY_LIMIT=256M
            - PHP_TIMEZONE=UTC
        networks:
            - app
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - .:/app
            - ../../shared/.env.local:/app/.env.local
            - ../../shared/images:/app/public/images/
