version: "3"

dotenv: [".env.local", ".env"]

vars:
  DOCKER_COMPOSE: '{{.TASK_DOCKER_COMPOSE | default "docker compose"}}'
  COMPOSER_INSTALL_ARGUMENTS: '{{.TASK_COMPOSER_INSTALL_ARGUMENTS | default ""}}'

tasks:
  default:
    cmds:
      - task --list
    silent: true

  # ---------------------------
  # Docker compose helpers
  # ---------------------------
  compose:
    cmds:
      - '{{.DOCKER_COMPOSE}} {{if .DOCKER_COMPOSE_PROFILES}}--profile {{.DOCKER_COMPOSE_PROFILES | splitList "," | join " --profile " }}{{end}} {{.CLI_ARGS}}'
    vars:
      DOCKER_COMPOSE_PROFILES: "{{.PROFILES | default .DOCKER_COMPOSE_PROFILES}}"

  compose-up:
    cmds:
      - task compose -- up --detach --remove-orphans {{if .COMPOSE_UP_WAIT}}--wait{{end}}
    silent: true

  # ---------------------------
  # Composer helpers
  # ---------------------------
  composer:
    cmds:
      - task compose -- exec phpfpm composer {{.CLI_ARGS}}
    silent: true

  composer-install:
    cmds:
      - task composer -- install {{.COMPOSER_INSTALL_ARGUMENTS}} {{.CLI_ARGS}}
    silent: true

  # ---------------------------
  # Project setup
  # ---------------------------
  start:
    desc: "Initial local setup"
    cmds:
      - task compose -- pull
      - task compose-up
      - task compose -- run --rm node npm install
      - task composer-install
      - task compose -- exec phpfpm bin/console doctrine:migrations:migrate --no-interaction
    silent: true

  watch:
    desc: "Watch for changes and re-build"
    cmds:
      - task compose -- logs --tail 0 --follow node

  data-provider:create:
    desc: "Create a data provider"
    cmds:
      - task compose -- exec phpfpm bin/console app:data-provider:create

  fixtures:load:
    desc: "Load fixtures"
    cmds:
      - task compose -- exec phpfpm bin/console doctrine:fixtures:load --no-interaction

  user:set-roles:
    desc: "Add a user"
    cmds:
      - task compose -- exec phpfpm bin/console app:user:set-roles
  # ---------------------------
  # Data synchronization
  # ---------------------------
  queue:all:
    desc: "Queue all sync jobs"
    cmds:
      - task compose -- exec phpfpm bin/console app:sync

  queue:projects:
    desc: "Sync projects"
    cmds:
      - task compose -- exec phpfpm bin/console app:sync projects

  queue:accounts:
    desc: "Sync accounts"
    cmds:
      - task compose -- exec phpfpm bin/console app:sync accounts

  queue:issues:
    desc: "Sync issues"
    cmds:
      - task compose -- exec phpfpm bin/console app:sync issues

  queue:worklogs:
    desc: "Sync worklogs"
    cmds:
      - task compose -- exec phpfpm bin/console app:sync worklogs

  queue:enqueue:
    desc: "Queue sync jobs"
    cmds:
      - task compose -- exec phpfpm bin/console app:queue-sync

  queue:consume-one:
    desc: "Run messenger worker - consume one"
    cmds:
      - task compose -- exec phpfpm bin/console messenger:consume async -vv --failure-limit 1

  queue:consume-all:
    desc: "Run messenger worker - consume all"
    cmds:
      - task compose -- exec phpfpm bin/console messenger:consume async -vv

  # ---------------------------
  # Coding standards
  # ---------------------------

  coding-standards:apply:
    desc: "Apply coding standards (all)"
    ignore_error: true
    cmds:
      - task compose -- exec phpfpm composer coding-standards-apply/php-cs-fixer
      - task compose -- exec phpfpm composer coding-standards-apply/twig-cs-fixer
      - task compose -- run --rm prettier 'assets/**/*.js' --write
      - task compose -- run --rm prettier 'assets/**/*.{css,scss}' --write
      - task compose -- run --rm prettier '**/*.{yml,yaml}' --write
      - task compose -- run --rm markdownlint --ignore LICENSE.md '*.md' docs/ --fix

  coding-standards:check:
    desc: "Check coding standards (all)"
    ignore_error: true
    cmds:
      - task composer -- coding-standards-check/php-cs-fixer
      - task composer -- coding-standards-check/twig-cs-fixer
      - task compose -- run --rm node npm run coding-standards-check/eslint
      - task compose -- run --rm prettier 'assets/**/*.{css,scss}' --check
      - task compose -- run --rm prettier '**/*.{yml,yaml}' --check
      - task compose -- run --rm node npm run coding-standards-check/markdownlint
      - task composer -- code-analysis/psalm
