when:
  - event: release

skip_clone: true

labels:
  zone: DMZ

steps:
  - name: Ansible playbook
    image: itkdev/ansible-plugin:1
    pull: true
    settings:
      id:
        from_secret: id
      secret:
        from_secret: secret
      host:
        from_secret: prod_economics_host
      path:
        from_secret: prod_economics_path
      user:
        from_secret: user
      playbook: 'release'
      pre_up:
        - itkdev-docker-compose-server run --rm phpfpm bin/console doctrine:migrations:migrate --no-interaction
        - itkdev-docker-compose-server run --rm phpfpm bin/console messenger:setup-transports
        - itkdev-docker-compose-server run --rm phpfpm bin/console cache:clear
      cron:
        # @TODO This should run with Symfony scheduler, see App\Command\QueueSyncCommand
        leantime-sync:
          minute: '22'
          hour: '*'
          day: '*'
          month: '*'
          weekday: '*'
          job: 'itkdev-docker-compose-server exec phpfpm bin/console app:sync'