on: pull_request

name: Review

env:
  COMPOSE_USER: runner

jobs:
  code-analysis:
    name: PHP - Code analysis (phpstan)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker network create frontend
          docker compose run --rm phpfpm composer install
          docker compose run --rm phpfpm composer code-analysis

  phpunit:
    name: Test suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test suite
        run: |
          docker network create frontend
          docker compose run --rm phpfpm composer install
          docker compose run --rm phpfpm vendor/bin/phpunit
