on: pull_request

name: Review

env:
  COMPOSE_USER: runner

jobs:
  validate-doctrine-schema:
    runs-on: ubuntu-latest
    name: Validate Doctrine Schema
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker network create frontend
          docker compose run --rm phpfpm composer install
          docker compose run --rm phpfpm bin/console doctrine:migrations:migrate --no-interaction
          docker compose run --rm phpfpm bin/console doctrine:schema:validate

  code-analysis:
    name: PHP - Code analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker network create frontend
          docker compose run --rm phpfpm composer install
          docker compose run --rm phpfpm composer code-analysis

  phpunit:
    name: Test suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build assets
        run: |
          docker network create frontend
          docker compose run --rm node npm install
          docker compose run --rm node npm run build

      - name: Test suite
        run: |
          docker network create frontend
          docker compose run --rm phpfpm composer install
          docker compose run -e XDEBUG_MODE=coverage --rm phpfpm vendor/bin/phpunit --coverage-clover=coverage/clover.xml

      - name: Enforce coverage threshold
        run: |
          docker compose run --rm phpfpm vendor/bin/coverage-check coverage/clover.xml 62
